### ISSUE TITLE
关于每日防侠提醒失效的问题

### ISSUE THREAD

**Issue by 2677505984** [diyigemt/arona#27]
console中的错误如下
`2023-05-20 08:00:01 E/ba-activity-pusher: Exception in coroutine Plugin net.diyigemt.arona of ba-activity-pusher
kotlin.UninitializedPropertyAccessException: lateinit property arona has not been initialized
        at net.diyigemt.arona-arona-1.0.14+20230325.mirai2.jar//net.diyigemt.arona.Arona.getArona(Arona.kt:50)
        at net.diyigemt.arona-arona-1.0.14+20230325.mirai2.jar//net.diyigemt.arona.Arona$sendMessageWithFile$1.invokeSuspend(Arona.kt:149)
        at net.diyigemt.arona-arona-1.0.14+20230325.mirai2.jar//net.diyigemt.arona.Arona$sendMessageWithFile$1.invoke(Arona.kt)
        at net.diyigemt.arona-arona-1.0.14+20230325.mirai2.jar//net.diyigemt.arona.Arona$sendMessageWithFile$1.invoke(Arona.kt)
        at net.diyigemt.arona-arona-1.0.14+20230325.mirai2.jar//net.diyigemt.arona.Arona$runSuspend$1.invokeSuspend(Arona.kt:126)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

![屏幕截图 2023-05-20 091116](https://github.com/diyigemt/arona/assets/127109493/49208748-80c3-435e-ac88-a576f2cad1c1)

**Comment by diyigemt** [comment]
配置一下console的自动登录就行，这个只影响启动时如果有快结束的活动时进行防侠
