### ISSUE TITLE
报错，但是不影响使用

### ISSUE THREAD

**Issue by Tamamoimoto** [diyigemt/arona#34]
2023-08-04 21:13:55 I/blue-archive-arona: 别名配置更新成功
2023-08-04 21:13:56 E/blue-archive-arona: Exception in coroutine Plugin net.diyigemt.arona of blue-archive-arona
java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.skia.Typeface
        at net.diyigemt.arona-arona-1.1.0.mirai2.jar//net.diyigemt.arona.util.ImageUtil$init$1.invokeSuspend(ImageUtil.kt:96)
        at net.diyigemt.arona-arona-1.1.0.mirai2.jar//net.diyigemt.arona.util.ImageUtil$init$1.invoke(ImageUtil.kt)
        at net.diyigemt.arona-arona-1.1.0.mirai2.jar//net.diyigemt.arona.util.ImageUtil$init$1.invoke(ImageUtil.kt)
        at net.diyigemt.arona-arona-1.1.0.mirai2.jar//net.diyigemt.arona.Arona$runSuspend$1.invokeSuspend(Arona.kt:136)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

系统版本：Linux armbian 5.15.58-flippy-75+o #148 SMP PREEMPT Sat Jul 30 11:32:27 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
Mirai console 2.15.0
这是什么原因呢

**Comment by diyigemt** [comment]
aarch64??  我打包的时候没有选择aarch64的运行时，我还以为不会有人再上边跑，我加上吧

**Comment by diyigemt** [comment]
试试 pre-release ? https://github.com/diyigemt/arona/releases/tag/v1.1.1

**Comment by Tamamoimoto** [comment]
好了，没有报错了0v0
