### ISSUE TITLE
活动绘制出错

### ISSUE THREAD

**Issue by bywhite0** [diyigemt/arona#35]
Log:
```
2023-08-05 19:47:10 W/blue-archive-arona: Exception in executing command `[mirai:source:ids=[18044], internalIds=[1255362879], from group *** to *** at 1691236029]/活动 jp`
java.lang.UnsatisfiedLinkError: 'void org.jetbrains.skia.CanvasKt._nScale(long, float, float)'
        at net.diyigemt.arona-arona-1.1.0.mirai2.jar[private]//org.jetbrains.skia.CanvasKt._nScale(Native Method)
        at net.diyigemt.arona-arona-1.1.0.mirai2.jar[private]//org.jetbrains.skia.CanvasKt.access$_nScale(Canvas.kt:1)
        at net.diyigemt.arona-arona-1.1.0.mirai2.jar[private]//org.jetbrains.skia.Canvas.scale(Canvas.kt:1093)
        at net.diyigemt.arona-arona-1.1.0.mirai2.jar//net.diyigemt.arona.util.ImageUtil.scale(ImageUtil.kt:69)
        at net.diyigemt.arona-arona-1.1.0.mirai2.jar//net.diyigemt.arona.util.ImageUtil.scale$default(ImageUtil.kt:64)
        at net.diyigemt.arona-arona-1.1.0.mirai2.jar//net.diyigemt.arona.util.ActivityUtil.createActivityImage(ActivityUtil.kt:719)
        at net.diyigemt.arona-arona-1.1.0.mirai2.jar//net.diyigemt.arona.command.ActivityCommand.send(ActivityCommand.kt:56)
        at net.diyigemt.arona-arona-1.1.0.mirai2.jar//net.diyigemt.arona.command.ActivityCommand.send$default(ActivityCommand.kt:55)
        at net.diyigemt.arona-arona-1.1.0.mirai2.jar//net.diyigemt.arona.command.ActivityCommand.sendJP(ActivityCommand.kt:43)
        at net.diyigemt.arona-arona-1.1.0.mirai2.jar//net.diyigemt.arona.command.ActivityCommand.activities$sendByLocale(ActivityCommand.kt:23)
        at net.diyigemt.arona-arona-1.1.0.mirai2.jar//net.diyigemt.arona.command.ActivityCommand.activities(ActivityCommand.kt:36)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:339)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:84)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:131)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:126)
        at chat-command-0.5.1.mirai.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:86)
        at chat-command-0.5.1.mirai.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:69)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

系统版本: Windows 10 x64 (10.0.19044)
Java版本: Open JDK 17
Mirai版本: 2.15.0

**Comment by diyigemt** [comment]
是偶发现象还是一直报错呢

**Comment by bywhite0** [comment]
> 是偶发现象还是一直报错呢

期间重启过几次Console，每次都会报错

**Comment by bywhite0** [comment]
对了，我同时安装了[bilibili-dynamic-mirai-plugin](https://github.com/Colter23/bilibili-dynamic-mirai-plugin)，不知道是否和依赖有关

**Comment by diyigemt** [comment]
有可能是和它的前置插件[mirai-skia-plugin](https://github.com/cssxsh/mirai-skia-plugin)冲突了，我看看能不能改到用它那边的不自己写了

**Comment by diyigemt** [comment]
试试 pre-release ? https://github.com/diyigemt/arona/releases/tag/v1.1.1

**Comment by bywhite0** [comment]
> 试试 pre-release ? https://github.com/diyigemt/arona/releases/tag/v1.1.1

实测 pre-release 没有问题，非常感谢
