### ISSUE TITLE
报错，且未加载中文字体，塔罗牌和抽卡无法使用

### ISSUE THREAD

**Issue by Fitz0527** [diyigemt/arona#41]
2023-08-16 12:18:14 E/blue-archive-arona: Exception in coroutine Plugin net.diyigemt.arona of blue-archive-arona
java.lang.UnsatisfiedLinkError: 'long org.jetbrains.skia.FontMgrKt._nDefault()'
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar[private]//org.jetbrains.skia.FontMgrKt._nDefault(Native Method)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar[private]//org.jetbrains.skia.FontMgrKt.access$_nDefault(FontMgr.kt:1)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar[private]//org.jetbrains.skia.FontMgr.<clinit>(FontMgr.kt:12)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.FontUtils.<clinit>(FontUtils.kt:31)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.ImageUtil$init$1.invokeSuspend(ImageUtil.kt:106)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.ImageUtil$init$1.invoke(ImageUtil.kt)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.ImageUtil$init$1.invoke(ImageUtil.kt)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.Arona$runSuspend$1.invokeSuspend(Arona.kt:139)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
以上是启动报错信息
2023-08-16 12:29:09 W/blue-archive-arona: Exception in executing command `[mirai:source:ids=[39995], internalIds=[1480745612], from group 961752345 to 635530773 at 1692160149]/塔罗牌`
 command owned by blue-archive-arona v1.1.2-RC with NormalMember(961752345)
java.lang.NullPointerException
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.command.TarotCommand.tarot(TarotCommand.kt:56)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:339)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:84)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:131)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:126)
        at chat-command-0.6.0.mirai2.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:98)
        at chat-command-0.6.0.mirai2.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:66)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
以上是塔罗牌报错信息，攻略防侠和活动等功能均可使用

**Comment by diyigemt** [comment]
中文字体问题请提供mirai的插件列表
塔罗牌问题请确认执行了安装步骤[第五步](https://doc.arona.diyigemt.com/install/arona#%E5%AE%89%E8%A3%85arona)替换数据库，因为RC版本发布没带上数据库文件

**Comment by Fitz0527** [comment]
替换数据库后功能正常了，字体问题好像没有影响使用

**Comment by Fitz0527** [comment]
![image](https://github.com/diyigemt/arona/assets/30644949/0aeb009d-7ae7-4707-adc2-43be62f73d34)
plugins文件夹中的所有插件如图
使用mclx list得到如下
2023-08-16 16:21:47 I/MCL Addon: Package: net.mamoe:mirai-console  Channel: maven-stable  Type: libs  Version: 2.15.0  Locked: false
2023-08-16 16:21:47 I/MCL Addon: Package: net.mamoe:mirai-console-terminal  Channel: maven-stable  Type: libs  Version: 2.15.0  Locked: false
2023-08-16 16:21:47 I/MCL Addon: Package: net.mamoe:mirai-core-all  Channel: maven-stable  Type: libs  Version: 2.15.0  Locked: false
2023-08-16 16:21:47 I/MCL Addon: Package: org.itxtech:mcl-addon  Channel: maven-stable  Type: plugins  Version: 2.1.1  Locked: false

**Comment by diyigemt** [comment]
有关于字体下载过程的报错吗，应该会有提示字体下载失败之类的

字体影响 防侠和活动功能

**Comment by Fitz0527** [comment]
没有提醒字体下载失败等报错，目前已有报错信息如下
启动时
2023-08-16 18:21:12 E/blue-archive-arona: Exception in coroutine Plugin net.diyigemt.arona of blue-archive-arona
java.lang.UnsatisfiedLinkError: 'long org.jetbrains.skia.FontMgrKt._nDefault()'
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar[private]//org.jetbrains.skia.FontMgrKt._nDefault(Native Method)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar[private]//org.jetbrains.skia.FontMgrKt.access$_nDefault(FontMgr.kt:1)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar[private]//org.jetbrains.skia.FontMgr.<clinit>(FontMgr.kt:12)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.FontUtils.<clinit>(FontUtils.kt:31)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.ImageUtil$init$1.invokeSuspend(ImageUtil.kt:106)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.ImageUtil$init$1.invoke(ImageUtil.kt)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.ImageUtil$init$1.invoke(ImageUtil.kt)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.Arona$runSuspend$1.invokeSuspend(Arona.kt:139)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
使用活动指令时
2023-08-16 18:22:06 W/blue-archive-arona: Exception in executing command `[mirai:source:ids=[40340], internalIds=[1896803146], from group 961752345 to 635530773 at 1692181325]/活动 jp`
 command owned by blue-archive-arona v1.1.2-RC with NormalMember(961752345)
java.lang.UnsatisfiedLinkError: 'long org.jetbrains.skia.SurfaceKt._nMakeRasterN32Premul(int, int)'
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar[private]//org.jetbrains.skia.SurfaceKt._nMakeRasterN32Premul(Native Method)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar[private]//org.jetbrains.skia.SurfaceKt.access$_nMakeRasterN32Premul(Surface.kt:1)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar[private]//org.jetbrains.skia.Surface$Companion.makeRasterN32Premul(Surface.kt:358)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.ImageUtil.createCalendarImage(ImageUtil.kt:28)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.ImageUtil.createCalendarImage$default(ImageUtil.kt:25)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.ActivityUtil.createActivityImage(ActivityUtil.kt:711)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.command.ActivityCommand.send(ActivityCommand.kt:58)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.command.ActivityCommand.send$default(ActivityCommand.kt:57)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.command.ActivityCommand.sendJP(ActivityCommand.kt:44)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.command.ActivityCommand.activities$sendByLocale(ActivityCommand.kt:23)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.command.ActivityCommand.activities(ActivityCommand.kt:37)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:339)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:84)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:131)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:126)
        at chat-command-0.6.0.mirai2.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:98)
        at chat-command-0.6.0.mirai2.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:66)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
以上

**Comment by diyigemt** [comment]
直接下载字体文件: https://arona.cdn.diyigemt.com/file/font/SourceHanSansCN-Normal.otf
放到 data/net.diyigemt.arona/font/ 试试

**Comment by Fitz0527** [comment]
data/net.diyigemt.arona/font/ 中已有字体文件，替换后还是出现同样问题
![67e0275261e2316c4594e3aa739b79e7](https://github.com/diyigemt/arona/assets/30644949/5c53f383-a403-4ee7-b040-4f46ce30daab)

**Comment by diyigemt** [comment]
试试这个?
[net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar.zip](https://github.com/diyigemt/arona/files/12359519/net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar.zip)

**Comment by Fitz0527** [comment]
还是不行，刚才又尝试另外从头创建Mirai2进行安装也是出现这个问题

**Comment by diyigemt** [comment]
我在这个版本加了更多调试信息，但是没改，当然不行，我是想看看报错能不能多点

提示有变多吗

**Comment by Fitz0527** [comment]
2023-08-17 09:07:32 E/blue-archive-arona: Exception in coroutine Plugin net.diyigemt.arona of blue-archive-arona
java.lang.UnsatisfiedLinkError: 'long org.jetbrains.skia.FontMgrKt._nDefault()'
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar[private]//org.jetbrains.skia.FontMgrKt._nDefault(Native Method)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar[private]//org.jetbrains.skia.FontMgrKt.access$_nDefault(FontMgr.kt:1)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar[private]//org.jetbrains.skia.FontMgr.<clinit>(FontMgr.kt:12)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.FontUtils.<clinit>(FontUtils.kt:31)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.ImageUtil$init$1.invokeSuspend(ImageUtil.kt:106)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.ImageUtil$init$1.invoke(ImageUtil.kt)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.ImageUtil$init$1.invoke(ImageUtil.kt)
        at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.Arona$runSuspend$1.invokeSuspend(Arona.kt:139)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
以上为目前的报错信息

**Comment by diyigemt** [comment]
没..没了?
能提供logs文件夹里最新的log文件吗，或者整个log文件夹打包

顺便检查一下`plugin-libraries/org/jetbrains/skiko/skiko-awt-runtime-windows-x64`这个文件夹和里边的东西存不存在

**Comment by Fitz0527** [comment]
额，很奇怪，把mirai-console重新换了个路径安装，全部插件从头开始安装后这个问题解决了，新的路径下没有报错提示，各功能也正常运行

**Comment by Fitz0527** [comment]
我再检查一下一号机的logs

**Comment by Fitz0527** [comment]
![6e7f485c82d6cb949087807d653d156b](https://github.com/diyigemt/arona/assets/30644949/ca218ae1-016a-442c-b7f3-c3e0d909eb59)
plugin-libraries/org/jetbrains/skiko/skiko-awt-runtime-windows-x64路径下内容如图

**Comment by diyigemt** [comment]
![)0~ S06AGTG23VGB5A9@W 7](https://github.com/diyigemt/arona/assets/41864956/e783fa8b-840c-4040-8b50-e857f05f9ee0)
就  就当它抽风吧啊哈哈
重装解决99%的问题
