### ISSUE TITLE
近期启动时会产生错误

### ISSUE THREAD

**Issue by Torther** [diyigemt/arona#52]
### 问题描述

在 arona 启动时，出现如下报错：
```
2023-10-25 23:36:34 I/blue-archive-arona: Source: STUDENT from GitHub already up to date.
2023-10-25 23:36:35 I/blue-archive-arona: Source: LOCALIZATION from GitHub already up to date.
2023-10-25 23:36:36 I/blue-archive-arona: Source: RAID from mirror already up to date.
2023-10-25 23:36:37 E/org.quartz.core.JobRunShell: Job Birthday.BirthdayJob threw an unhandled Exception: 
java.time.format.DateTimeParseException: Text '2023/-' could not be parsed at index 6
        at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2106)
        at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:2008)
        at java.base/java.time.LocalDate.parse(LocalDate.java:435)
        at net.diyigemt.arona-1.1.4-RC2.mirai2.jar//net.diyigemt.arona.util.scbaleDB.SchaleDBDataSyncService$BirthdayJob.getBirthdayList(SchaleDBDataSyncService.kt:68)
        at net.diyigemt.arona-1.1.4-RC2.mirai2.jar//net.diyigemt.arona.util.scbaleDB.SchaleDBDataSyncService$BirthdayJob.execute(SchaleDBDataSyncService.kt:62)
        at net.diyigemt.arona-1.1.4-RC2.mirai2.jar[private]//org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at net.diyigemt.arona-1.1.4-RC2.mirai2.jar[private]//org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

2023-10-25 23:36:37 E/org.quartz.core.ErrorLogger: Job (Birthday.BirthdayJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.time.format.DateTimeParseException: Text '2023/-' could not be parsed at index 6]
        at net.diyigemt.arona-1.1.4-RC2.mirai2.jar[private]//org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at net.diyigemt.arona-1.1.4-RC2.mirai2.jar[private]//org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.time.format.DateTimeParseException: Text '2023/-' could not be parsed at index 6
        at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2106)
        at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:2008)
        at java.base/java.time.LocalDate.parse(LocalDate.java:435)
        at net.diyigemt.arona-1.1.4-RC2.mirai2.jar//net.diyigemt.arona.util.scbaleDB.SchaleDBDataSyncService$BirthdayJob.getBirthdayList(SchaleDBDataSyncService.kt:68)
        at net.diyigemt.arona-1.1.4-RC2.mirai2.jar//net.diyigemt.arona.util.scbaleDB.SchaleDBDataSyncService$BirthdayJob.execute(SchaleDBDataSyncService.kt:62)
        at net.diyigemt.arona-1.1.4-RC2.mirai2.jar[private]//org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 more

2023-10-25 23:36:39 W/blue-archive-arona: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
2023-10-25 23:36:39 W/blue-archive-arona: 数据同步失败，无法保证数据准确性
```
ChatGPT 解答如下：
```
你遇到的错误与 java.time.format.DateTimeParseException 相关。这个异常是在尝试解析日期和时间字符串时出现问题时抛出的，而在你的情况下，它似乎发生在一个使用Quartz调度器库的Java应用程序中。

以下是错误消息告诉我们的内容：

错误起因于一个名为 "Birthday.BirthdayJob" 的作业。
具体问题与解析一个值为 '2023/-' 的日期或时间字符串有关。错误消息指出，这个文本在索引6处无法解析。
错误发生在一个名为 SchaleDBDataSyncService$BirthdayJob 的类或函数中，具体在同一类的 getBirthdayList 函数的第68行和 execute 函数的第62行。
要解决此问题，你需要检查 SchaleDBDataSyncService$BirthdayJob 类中的代码，并查找尝试解析日期或时间字符串的位置。特别关注字符串 '2023/-'，并检查它为什么不符合有效日期格式。

确保被解析的日期字符串处于有效格式（例如，日期的格式为 'YYYY-MM-DD'）并且不包含任何意外的字符。你可能需要添加错误处理来处理日期字符串不符合预期格式的情况，或在尝试解析之前更正日期字符串。
```

### arona 版本

1.1.4-RC2

**Comment by bywhite0** [comment]
Duplicate with #49

**Comment by bywhite0** [comment]
Duplicate with #49

edit: 一样是 SchaleDB 数据结构修改引发的问题

**Comment by diyigemt** [comment]
其实是我懒得修了(，这个只影响到列车活动之后的学生不会提示生日而已
毕竟现在框架系的机器人都在半死不活的状态，新项目在写了，正好QQ官方快开放接口了，到时候直接转正

**Comment by Torther** [comment]
> 其实是我懒得修了(，这个只影响到列车活动之后的学生不会提示生日而已 毕竟现在框架系的机器人都在半死不活的状态，新项目在写了，正好QQ官方快开放接口了，到时候直接转正

期待转正（

**Comment by diyigemt** [comment]
试试 [v1.1.4](https://github.com/diyigemt/arona/releases/tag/v1.1.4)，另外关注 [arona-reborn](https://github.com/diyigemt/arona-reborn) 谢谢喵
