### ISSUE TITLE
登陆bot时提示code=16错误

### ISSUE THREAD

**Issue by Shigaharuki3012** [diyigemt/arona#55]
大佬好！托您的福今天成功登陆并配置了一段时间，晚上重新登陆时提示如下错误：
```
net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl.doLogin(SsoProcessor.kt:528)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3378587540), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]

2023-11-10 01:18:08 I/Bot.3378587540: Bot cancelled: Bot closed

```
第一次上线测试时风控过，也用人脸验证了，现在手机也能正常登陆，但是在mcl输入登陆指令后就会返回这个错误。能问下是什么原因吗？

**Comment by Shigaharuki3012** [comment]
已解决，退出mcl时不能直接关闭，需要stop指令。
如果提示这个的话就把bots/.../cache删除后重新登即可。
