### ISSUE TITLE
提交一个8月16日通过重新安装和重启后解决的bug的解决方法

### ISSUE THREAD

**Issue by Fitz0527** [diyigemt/arona#57]
### 问题描述

windows10 平台
启动时出现如下列报错
2023-xx-xx xx:xx:xx E/blue-archive-arona: Exception in coroutine Plugin net.diyigemt.arona of blue-archive-arona
java.lang.UnsatisfiedLinkError: 'long org.jetbrains.skia.FontMgrKt._nDefault()'
》》》》》
检查字体文件未缺失，后检查推测是缺失skiko插件，该错误对总体功能使用无影响，主要影响有关防侠等图片生成过程，导致防侠无法使用。
解决方法： 
安装SkikoMirai
https://github.com/LaoLittle/SkikoMirai 
完成安装后报错消失，防侠等功能正常使用

### arona 版本

1.1.4-RC2

### 系统日志

```shell
2023-xx-xx xx:xx:xx E/blue-archive-arona: Exception in coroutine Plugin net.diyigemt.arona of blue-archive-arona
java.lang.UnsatisfiedLinkError: 'long org.jetbrains.skia.FontMgrKt._nDefault()'
at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar[private]//org.jetbrains.skia.FontMgrKt._nDefault(Native Method)
at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar[private]//org.jetbrains.skia.FontMgrKt.access$_nDefault(FontMgr.kt:1)
at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar[private]//org.jetbrains.skia.FontMgr.(FontMgr.kt:12)
at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.FontUtils.(FontUtils.kt:31)
at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.ImageUtil$init$1.invokeSuspend(ImageUtil.kt:106)
at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.ImageUtil$init$1.invoke(ImageUtil.kt)
at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.util.ImageUtil$init$1.invoke(ImageUtil.kt)
at net.diyigemt.arona-arona-1.1.2-RC.mirai2.jar//net.diyigemt.arona.Arona$runSuspend$1.invokeSuspend(Arona.kt:139)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by Nuist666** [comment]
和我的报错一样，不过我是在Aidlux上跑的，有没有什么解决方案

**Comment by Nuist666** [comment]
我也遇到了同样的问题，https://github.com/diyigemt/arona/issues/56
根据提示安装了
![image](https://github.com/diyigemt/arona/assets/104258411/c7af892f-a4bf-43eb-9a63-985209514d2a)
但是安装后出现新的报错：
![image](https://github.com/diyigemt/arona/assets/104258411/48d4336d-13a2-4951-8d19-151e1b8909ed)
查了一下看到这个issue：https://github.com/oven-sh/bun/issues/255
想起来我在安装mcl时用的musl，是不是这个问题，谢谢

**Comment by diyigemt** [comment]
试试 [v1.1.4](https://github.com/diyigemt/arona/releases/tag/v1.1.4)，另外关注 [arona-reborn](https://github.com/diyigemt/arona-reborn) 谢谢喵
