### ISSUE TITLE
防侠推送异常

### ISSUE THREAD

**Issue by Nuist666** [diyigemt/arona#60]
### 问题描述

设置了22点防侠推送，到了22点就报错。发送 /活动 命令正常  
`E/org.quartz.core.JobRunShell: Job ActivityNotify.ActivityNotifyJob threw an unhandled Exception:
org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'ActivityNotifyOneHour.ActivityNotifyOneHour-cn-22-Job', because one already exists with this identification.
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.simpl.RAMJobStore.storeJob(RAMJobStore.java:279)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.simpl.RAMJobStore.storeJobAndTrigger(RAMJobStore.java:251)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:855)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:249)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.quartz.QuartzProvider.createSingleTask(QuartzProvider.kt:40)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.advance.ActivityNotify$ActivityNotifyJob.doInsert(ActivityNotify.kt:97)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.advance.ActivityNotify$ActivityNotifyJob.doInsert$default(ActivityNotify.kt:92)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.advance.ActivityNotify$ActivityNotifyJob.insertAlert(ActivityNotify.kt:126)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.advance.ActivityNotify$ActivityNotifyJob.execute(ActivityNotify.kt:61)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

2024-03-06 22:00:00 E/org.quartz.core.ErrorLogger: Job (ActivityNotify.ActivityNotifyJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'ActivityNotifyOneHour.ActivityNotifyOneHour-cn-22-Job', because one already exists with this identification.]
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'ActivityNotifyOneHour.ActivityNotifyOneHour-cn-22-Job', because one already exists with this identification.
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.simpl.RAMJobStore.storeJob(RAMJobStore.java:279)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.simpl.RAMJobStore.storeJobAndTrigger(RAMJobStore.java:251)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:855)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:249)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.quartz.QuartzProvider.createSingleTask(QuartzProvider.kt:40)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.advance.ActivityNotify$ActivityNotifyJob.doInsert(ActivityNotify.kt:97)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.advance.ActivityNotify$ActivityNotifyJob.doInsert$default(ActivityNotify.kt:92)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.advance.ActivityNotify$ActivityNotifyJob.insertAlert(ActivityNotify.kt:126)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.advance.ActivityNotify$ActivityNotifyJob.execute(ActivityNotify.kt:61)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 more`  

### 复现

因为Mirai签名的问题，替换 mirai 实现为 Onebot 进行无缝迁移，使用了[Overflow](https://github.com/MrXiaoM/Overflow)项目，[替换 mirai-core 类库](https://github.com/MrXiaoM/Overflow/blob/main/docs/install/Raw.md)并使用[LiteloaderQQNT的OneBot API插件](https://github.com/LLOneBot/LLOneBot)。除了防侠推送功能其他功能正常。在迁移前是正常的。  
请问是不是因为替换mirai-core类库导致的问题，是的话我到那边去问问？

### arona 版本

1.1.4

### 其他插件及版本

bilibili-dynamic-mirai-plugin-3.2.11.mirai2.jar  
chat-command-0.6.0.mirai2.jar  
mcl-addon-2.1.1.jar  
mirai-api-http-2.9.1.mirai2.jar  
mirai-skia-plugin-1.3.2.mirai2.jar  
MiraiSongPlugin-2.7-1.2.1.jar  
NetworkTools-1.1.2.mirai2.jar

### 系统日志

```shell
2024-03-06 22:00:00 E/org.quartz.core.JobRunShell: Job ActivityNotify.ActivityNotifyJob threw an unhandled Exception:
org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'ActivityNotifyOneHour.ActivityNotifyOneHour-cn-22-Job', because one already exists with this identification.
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.simpl.RAMJobStore.storeJob(RAMJobStore.java:279)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.simpl.RAMJobStore.storeJobAndTrigger(RAMJobStore.java:251)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:855)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:249)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.quartz.QuartzProvider.createSingleTask(QuartzProvider.kt:40)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.advance.ActivityNotify$ActivityNotifyJob.doInsert(ActivityNotify.kt:97)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.advance.ActivityNotify$ActivityNotifyJob.doInsert$default(ActivityNotify.kt:92)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.advance.ActivityNotify$ActivityNotifyJob.insertAlert(ActivityNotify.kt:126)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.advance.ActivityNotify$ActivityNotifyJob.execute(ActivityNotify.kt:61)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

2024-03-06 22:00:00 E/org.quartz.core.ErrorLogger: Job (ActivityNotify.ActivityNotifyJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'ActivityNotifyOneHour.ActivityNotifyOneHour-cn-22-Job', because one already exists with this identification.]
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'ActivityNotifyOneHour.ActivityNotifyOneHour-cn-22-Job', because one already exists with this identification.
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.simpl.RAMJobStore.storeJob(RAMJobStore.java:279)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.simpl.RAMJobStore.storeJobAndTrigger(RAMJobStore.java:251)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:855)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:249)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.quartz.QuartzProvider.createSingleTask(QuartzProvider.kt:40)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.advance.ActivityNotify$ActivityNotifyJob.doInsert(ActivityNotify.kt:97)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.advance.ActivityNotify$ActivityNotifyJob.doInsert$default(ActivityNotify.kt:92)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.advance.ActivityNotify$ActivityNotifyJob.insertAlert(ActivityNotify.kt:126)
        at net.diyigemt.arona-1.1.4.mirai2.jar//net.diyigemt.arona.advance.ActivityNotify$ActivityNotifyJob.execute(ActivityNotify.kt:61)
        at net.diyigemt.arona-1.1.4.mirai2.jar[private]//org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 more

2024-03-06 22:00:04 W/blue-archive-arona: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
2024-03-06 22:00:04 W/blue-archive-arona: 数据同步失败，无法保证数据准确性
```

**Comment by Nuist666** [comment]
今天无意间看到了刚启动时出现了有关QuartzScheduler的信息：  
```
2024-03-25 21:22:28 I/org.quartz.impl.StdSchedulerFactory: Using default implementation for ThreadExecutor
2024-03-25 21:22:28 I/org.quartz.simpl.SimpleThreadPool: Job execution threads will use class loader of thread: main
2024-03-25 21:22:28 I/org.quartz.core.SchedulerSignalerImpl: Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2024-03-25 21:22:28 I/org.quartz.core.QuartzScheduler: Quartz Scheduler v.2.3.2 created.
2024-03-25 21:22:28 I/org.quartz.simpl.RAMJobStore: RAMJobStore initialized.
2024-03-25 21:22:28 I/org.quartz.core.QuartzScheduler: Scheduler meta-data: Quartz Scheduler (v2.3.2) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2024-03-25 21:22:28 I/org.quartz.impl.StdSchedulerFactory: Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
2024-03-25 21:22:28 I/org.quartz.impl.StdSchedulerFactory: Quartz scheduler version: 2.3.2
2024-03-25 21:22:28 I/org.quartz.core.QuartzScheduler: Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2024-03-25 21:22:28 I/blue-archive-arona: arona loaded  
```
![image](https://github.com/diyigemt/arona/assets/104258411/ec6df174-370e-4a64-9f1b-2c4d49897e10)

然后到22点报错：
···
2024-03-25 22:00:00 E/org.quartz.core.JobRunShell: Job ActivityNotify.ActivityNotifyJob threw an unhandled Exception:
org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'ActivityNotifyOneHour.ActivityNotifyOneHour-en-22-Job', because one already exists with this identification.
···
![image](https://github.com/diyigemt/arona/assets/104258411/c99588d9-92c7-4097-8204-1befc4c9c668)  
请问是什么问题
![test](https://github.com/diyigemt/arona/assets/104258411/7475a3b5-63b4-48fc-b842-bd48b597e3a3)

**Comment by diyigemt** [comment]
![9f6bc65ef1b40ae5a04b6659468d5a49](https://github.com/diyigemt/arona/assets/41864956/3f0f672d-7329-4e4f-bcca-4b9edee539e3)
我努力一下

**Comment by Nuist666** [comment]
顺便问一下，现在新部署的话uuid会register failed，用的是之前v1后端，请问有没有影响呢

**Comment by diyigemt** [comment]
没有 v2现在给v1做了兼容  register没实现不影响
